networks:
  zeebe_network:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - path.repo=/usr/local/els-snapshots
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - zeebe_network
    restart: always
    volumes:
      - ./els-snapshots:/usr/local/els-snapshots

  opensearch:
    image: opensearchproject/opensearch:2.16.0
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=yourStrongPassword123!
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    ports:
      - 9205:9200
      - 9605:9605 # required for Performance Analyzer
    networks:
      - zeebe_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    ports:
      - 5601:5601
    environment:
      - elasticsearch.hosts=elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - zeebe_network

  zeebe:
    container_name: zeebe-${DATABASE}
    image: camunda/zeebe:SNAPSHOT
    environment:
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
      #- "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n"
    ports:
      - 26500:26500
      - 9601:9600
      - 8089:8080
    depends_on:
      - ${DATABASE}
    networks:
      - zeebe_network
    env_file:
      - ./config/envs/.env.database.${DATABASE}
    restart: always

  tasklist:
    container_name: tasklist-${DATABASE}
    image: camunda/tasklist:SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=dev,dev-data,auth
    depends_on:
      - ${DATABASE}
      - zeebe
    env_file:
      - ./config/envs/.env.database.${DATABASE}
    networks:
      - zeebe_network
    restart: always

  operate:
    container_name: tasklist-operate-${DATABASE}
    image: camunda/operate:SNAPSHOT
    ports:
      - 8088:8080
    environment:
      - spring.profiles.active=dev,auth
    depends_on:
      - ${DATABASE}
      - zeebe
    env_file:
      - ./config/envs/.env.database.${DATABASE}
    networks:
      - zeebe_network
    restart: always

  zeebe-e2e:
    container_name: zeebe-e2e
    image: camunda/zeebe:SNAPSHOT
    environment:
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
      - ZEEBE_BROKER_NETWORK_HOST=zeebe-e2e
      - ZEEBE_BROKER_GATEWAY_NETWORK_PORT=26503
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_PREFIX=e2e
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
      - ZEEBE_BROKER_GATEWAY_ENABLE=true
      #- "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n"
    ports:
      - 26503:26503
      - 8001:8000
      - 8088:8080
    networks:
      - zeebe_network
    restart: always

  tasklist-e2e:
    container_name: tasklist-e2e
    image: camunda/tasklist:SNAPSHOT
    ports:
      - 8081:8080
    environment:
      - camunda.tasklist.elasticsearch.indexPrefix=e2etasklist
      - camunda.tasklist.zeebeElasticsearch.prefix=e2e
      - camunda.tasklist.zeebe.gatewayAddress=zeebe-e2e:26503
      - camunda.tasklist.zeebe.restAddress=http://zeebe-e2e:8088
      - camunda.tasklist.importer.readerBackoff=0
      - camunda.tasklist.importer.schedulerBackoff=0
      - spring.profiles.active=e2e-test
    depends_on:
      - elasticsearch
      - zeebe-e2e
    networks:
      - zeebe_network
    env_file:
      - ./config/envs/.env.database.${DATABASE}
    restart: always

  tasklist-sso:
    container_name: tasklist-sso
    image: camunda/tasklist:SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=dev,dev-data,sso-auth
      - camunda.tasklist.auth0.backendDomain=camunda-dev.eu.auth0.com
      - camunda.tasklist.auth0.claimName=https://camunda.com/orgs
      - camunda.tasklist.auth0.clientId=CLGSo9RQ1K290Fvy2ohDomndvLR3Qgl3
      - camunda.tasklist.auth0.clientSecret=${ZEEBE_TASKLIST_AUTH0_CLIENTSECRET}
      - camunda.tasklist.auth0.domain=weblogin.cloud.ultrawombat.com
      - camunda.tasklist.auth0.organization=ebe81097-6657-4481-8fba-be5d94cac4ce
      - graphql.playground.enabled=true
      - graphql.playground.settings.request.credentials=include
    depends_on:
      - elasticsearch
      - zeebe
    env_file:
      - ./config/envs/.env.database.${DATABASE}
    networks:
      - zeebe_network
    restart: always

  camunda:
    container_name: camunda
    image: camunda/camunda:SNAPSHOT
    environment:
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
      - SPRING_PROFILES_ACTIVE=operate,tasklist,broker,dev,dev-data,auth
      - ZEEBE_BROKER_CLUSTER_PARTITIONS_COUNT=2
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
      - ZEEBE_BROKER_GATEWAY_ENABLE=true
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=camunda:26500
      - CAMUNDA_TASKLIST_ZEEBE_RESTADDRESS=http://camunda:8080
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=camunda:26500
    ports:
      - 26500:26500
      - 9600:9600
      - 8080:8080
    depends_on:
      - elasticsearch
    networks:
      - zeebe_network
    restart: always
