---
# Default values for C8 Self-Managed Camunda Preview Environments

ingress:
  # Defines the domain under which to expose the ingress
  domain: camunda.camunda.cloud

git:
  # will be set by the "deploy-preview-env" action
  branch: master
  # Defines the repository URL to use for annotating resources
  repoUrl: https://github.com/camunda/camunda

# Configuration of the camunda-platform chart, in particular we disable some features that
# we don't want to deploy. We also change the `fullNameOverride` and `zeebeClusterName`
# to simpler values, so we don't duplicate
# the ReleaseName everwhere (as that's already reflected in the Namespace).
camunda-platform:
  connectors:
    enabled: false

  identity:
    fullnameOverride: identity
    nodeSelector:
      cloud.google.com/gke-nodepool: previews
    tolerations:
    - key: "previews"
      operator: "Exists"
      effect: "NoSchedule"
    keycloak:
      # fullnameOverride: keycloak
      auth:
        createAdminUser: true
        adminUser: admin
        adminPassword: admin
      extraEnvVars:
      - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
        value: "true"
      externalDatabase:
        password: postgresql
      nodeSelector:
        cloud.google.com/gke-nodepool: previews
      tolerations:
      - key: "previews"
        operator: "Exists"
        effect: "NoSchedule"
      postgresql:
        fullnameOverride: postgresql
        # fixing the password to avoid failure on restart of keycloak pod
        # each time the keycloak pod restarts need a restart of the database cuz a random password is given
        auth:
          password: postgresql
        primary:
          persistence:
            enabled: false
          nodeSelector:
            cloud.google.com/gke-nodepool: previews
          tolerations:
          - key: "previews"
            operator: "Exists"
            effect: "NoSchedule"

  operate:
    fullnameOverride: operate
    image:
      registry: registry.camunda.cloud
      repository: team-camunda/operate
      pullSecrets:
        - name: dockerhub-registry
        - name: registry-camunda-cloud
      # will be set by the "deploy-preview-env" action
      tag: "pr-1882c176b432bd532dac75c460ef95cbfc281cab"
    env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-data
    nodeSelector:
      cloud.google.com/gke-nodepool: previews
    tolerations:
    - key: "previews"
      operator: "Exists"
      effect: "NoSchedule"

  optimize:
    fullnameOverride: optimize
    image:
      registry: registry.camunda.cloud
      repository: team-camunda/optimize
      pullSecrets:
      - name: dockerhub-registry
      - name: registry-camunda-cloud
      # will be set by the "deploy-preview-env" action
      tag: "pr-1882c176b432bd532dac75c460ef95cbfc281cab"
    env:
    - name: CAMUNDA_OPTIMIZE_IMPORT_CUSTOMER_ONBOARDING
      value: "true"
    nodeSelector:
      cloud.google.com/gke-nodepool: previews
    tolerations:
    - key: "previews"
      operator: "Exists"
      effect: "NoSchedule"

  tasklist:
    fullnameOverride: tasklist
    image:
      registry: registry.camunda.cloud
      repository: team-camunda/taslist
      pullSecrets:
        - name: dockerhub-registry
        - name: registry-camunda-cloud
      # will be set by the "deploy-preview-env" action
      tag: "pr-1882c176b432bd532dac75c460ef95cbfc281cab"
    nodeSelector:
      cloud.google.com/gke-nodepool: previews
    tolerations:
    - key: "previews"
      operator: "Exists"
      effect: "NoSchedule"

  # Configuration for ElasticSearch. Persistence is disabled by default,
  # and we're setting some reasonable defaults for the `PersistentVolumeClaim` size
  # in order to avoid being too wasteful.
  # Feel free to enable persistence and adjust storage on a per-branch level whenever needed.
  elasticsearch:
    # https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/values.yaml

    # will be set by the "deploy-preview-env" action
    image:
      tag: 7.17.14

    master:
      replicaCount: 1
      containerSecurityContext:
        capabilities:
          add:
          - IPC_LOCK
      persistence:
        # Disable the creation of persistent volumes.
        # Feel free to enable persistence and adjust storage on a per-branch level whenever needed.
        enabled: false
        # Defines a reasonable default for the `elasticsearch` StatefulSet, for when persistence is enabled.
        size: 2Gi
      resources:
        limits:
          cpu: '2'
          memory: 2Gi
        requests:
          cpu: '1'
          memory: 2Gi
      nodeSelector:
        cloud.google.com/gke-nodepool: previews
      tolerations:
      - key: "previews"
        operator: "Exists"
        effect: "NoSchedule"

  zeebe:
    fullnameOverride: zeebe
    clusterSize: 1
    partitionCount: 1
    replicationFactor: 1
    # Disable the creation of persistent volumes.
    # Feel free to enable persistence and adjust storage on a per-branch level whenever needed.
    persistenceType: local
    # Defines a reasonable default for the `zeebe` StatefulSet, for when persistence is enabled.
    pvcSize: 2Gi
    nodeSelector:
      cloud.google.com/gke-nodepool: previews
    tolerations:
    - key: "previews"
      operator: "Exists"
      effect: "NoSchedule"

  zeebe-gateway:
    fullnameOverride: zeebe-gateway
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-nodepool: previews
    tolerations:
    - key: "previews"
      operator: "Exists"
      effect: "NoSchedule"


# Configuration of global values as required by the camunda-platform chart and
# to comply with Infra best practices.
global:
  labels:
    camunda.cloud/source: argocd
    camunda.cloud/managed-by: Helm
    app: camunda-camunda-cloud  # Should be overridden by Argo app
    team: camunda
  identity:
    auth:
      # # Identity.auth.enabled if true, enables the Identity authentication otherwise basic-auth will be used on all services.
      # enabled: false

      # will be set by the "deploy-preview-env" action
      publicIssuerUrl: "https://keycloak-test.camunda.camunda.cloud/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://test.camunda.camunda.cloud"
      optimize:
        redirectUrl: "https://test.camunda.camunda.cloud"
      tasklist:
        redirectUrl: "https://test.camunda.camunda.cloud"
  image:
    pullSecrets:
    - name: dockerhub-registry
  # still required by some subcharts (e.g. elasticsearch)
  imagePullSecrets:
  - name: dockerhub-registry
  zeebeClusterName: zeebe
