name: Optimize Release Camunda Optimize C8

on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        required: true
        description: "Version to release. Applied to pom.xml and Git tag"
        default: "0.0.0"
      DEVELOPMENT_VERSION:
        required: true
        description: "Next development version"
        default: "0.1.0-SNAPSHOT"
      BRANCH:
        required: true
        description: "The branch used for the release checkout"
        default: "release/0.0.0"
      DOCKER_LATEST:
        required: true
        description: "Should the docker image be tagged as latest?"
        type: boolean
        default: true
      IS_DRY_RUN:
        required: true
        description: "Is this a dry run?"
        type: boolean
        default: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Execute Release
    runs-on: gcp-core-2-release
    env:
      DOCKER_IMAGE_TEAM: registry.camunda.cloud/optimize-ee/optimize
      DOCKER_IMAGE_DOCKER_HUB: camunda/optimize
      DOCKER_LATEST_TAG: latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3.0.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/infra/ci/common CAMUNDA_NEXUS_USR;
            secret/data/products/infra/ci/common CAMUNDA_NEXUS_PSW;
            secret/data/products/optimize/ci/camunda-optimize REGISTRY_HUB_DOCKER_COM_USR;
            secret/data/products/optimize/ci/camunda-optimize REGISTRY_HUB_DOCKER_COM_PSW;

      - name: Log Input Variables
        run: |
          echo "RELEASE_VERSION: ${{ inputs.RELEASE_VERSION }}"
          echo "DEVELOPMENT_VERSION: ${{ inputs.DEVELOPMENT_VERSION }}"
          echo "BRANCH: ${{ inputs.BRANCH }}"
          echo "DOCKER_LATEST: ${{ inputs.DOCKER_LATEST }}"
          echo "IS_DRY_RUN: ${{ inputs.IS_DRY_RUN }}"

      - name: "Read Java / Version Info"
        id: "pom-info"
        uses: YunaBraska/java-info-action@main

      - name: Setup Maven
        uses: ./.github/actions/setup-maven
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Is current release major or minor.
        id: release-type
        env:
          RELEASE_VERSION: ${{ github.event.inputs.RELEASE_VERSION || '0.0.0' }}
        run: |
          is_major_or_minor="false"
          is_patch="true"
          is_rc="true"
          is_alpha="true"
          patch_version=$(echo "$RELEASE_VERSION" | cut -d. -f3)
          if [[ ! "$patch_version" == *"-"* ]] && [[ "$patch_version" == "0" ]]; then
            is_major_or_minor="true"
            is_patch="false"
            echo "is_patchr=$is_patch"
            echo "is_major_or_minor=$is_major_or_minor"
          fi
          if [[ ! $RELEASE_VERSION =~ rc[0-9]+$ ]]; then
            is_rc="false"
          fi
          if [[ ! $RELEASE_VERSION =~ alpha[0-9]+$ ]]; then
            is_alpha="false"
          fi
          echo "is_major_or_minor=$is_major_or_minor" >> "$GITHUB_OUTPUT"
          echo "is_patch=$is_patch" >> "$GITHUB_OUTPUT"
          echo "is_rc=$is_rc" >> "$GITHUB_OUTPUT"
          echo "is_alpha=$is_alpha" >> "$GITHUB_OUTPUT"

      - name: Install common tooling (buildx) # required on self-hosted runners
        uses: camunda/infra-global-github-actions/common-tooling@main
        with:
          buildx-enabled: true
          java-enabled: false
          node-enabled: false
          python-enabled: false
          yarn-enabled: false

      - name: Define common variables
        id: define-values
        uses: ./.github/actions/git-environment

      - name: Expose common variables as Env
        run: |
          {
            echo "DOCKER_LATEST=${{ github.event.inputs.DOCKER_LATEST || true}}"
            echo "DEVELOPMENT_VERSION=${{ github.event.inputs.DEVELOPMENT_VERSION || '0.1.0-SNAPSHOT' }}"
            echo "RELEASE_VERSION=${{ github.event.inputs.RELEASE_VERSION || '0.0.0' }}"
            echo "BRANCH=${{ github.event.inputs.BRANCH || github.ref_name }}"
            echo "REVISION=${{ steps.define-values.outputs.git_commit_hash }}"
            echo "MAJOR_OR_MINOR=${{ steps.release-type.outputs.is_major_or_minor }}"
            echo "IS_PATCH=${{ steps.release-type.outputs.is_patch }}"
            echo "IS_ALPHA=${{ steps.release-type.outputs.is_alpha }}"
            echo "IS_RC=${{ steps.release-type.outputs.is_rc }}"
            echo "IS_DRY_RUN=${{ github.event.inputs.IS_DRY_RUN || 'true' }}"
            echo "TAG=${{ github.event.inputs.RELEASE_VERSION || '0.0.0' }}-optimize"
          } >> "$GITHUB_ENV"

      - name: Login to prod Harbor docker registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: registry.camunda.cloud
          username: ${{ steps.secrets.outputs.CAMUNDA_NEXUS_USR }}
          password: ${{ steps.secrets.outputs.CAMUNDA_NEXUS_PSW }}

      - name: Login to docker hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          username: ${{ steps.secrets.outputs.REGISTRY_HUB_DOCKER_COM_USR }}
          password: ${{ steps.secrets.outputs.REGISTRY_HUB_DOCKER_COM_PSW }}

      - name: Checkout release branch
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 0

      - name: Configure GitHub user
        run: |
          git config --global user.name "optimize-release"
          git config --global user.email "ci@optimize.camunda.cloud"

      - name: Prepare release
        run: |
          mvn -f optimize \
            -DpushChanges=false \
            -DskipTests=true \
            -Prelease,runAssembly \
            release:prepare \
            -Dtag=${TAG} \
            -DreleaseVersion="${RELEASE_VERSION}" \
            -DdevelopmentVersion="${DEVELOPMENT_VERSION}" \
            -Darguments="-Dmaven.deploy.skip=${IS_DRY_RUN} -DskipTests -DskipNexusStagingDeployMojo=${IS_DRY_RUN} -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -f pom.xml" \
            -B \
            --fail-at-end \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - name: Push changes
        if: env.IS_DRY_RUN == 'false'
        run: |
          git push --tags
          git push --all

      - name: Perform release
        run: |
          mvn -f optimize \
            -DlocalCheckout=true \
            -DskipTests=true \
            -B \
            --fail-at-end \
            -Prelease,runAssembly \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            release:perform \
            -Darguments="-Dmaven.deploy.skip=${IS_DRY_RUN} -DskipTests -DskipNexusStagingDeployMojo=${IS_DRY_RUN} -B --fail-at-end -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -f pom.xml"

      - name: Remove tag for RC release
        if: env.IS_RC == 'true'
        run: |
          git tag -d ${TAG}
          git push origin :refs/tags/${TAG}

      - name: Auto-update previous version
        run: |
          if [ "$IS_PATCH" = "false" ]; then
            # only major / minor GA (.0) release versions will trigger an auto-update of previousVersion property.
            echo "Auto-updating previousVersion property as release version is a valid major/minor version."
            git fetch
            git checkout ${BRANCH}
            sed -i "s/project.previousVersion>.*</project.previousVersion>${RELEASE_VERSION}</g" pom.xml
            git add pom.xml
            # This is needed to not abort the job in case 'git diff' returns a status different from 0
            set +e
            git diff --staged --quiet
            diff_result=$?
            set -e

            if [ $diff_result -ne 0 ]; then
              git commit -m "chore: update previousVersion to new release version ${RELEASE_VERSION}"
              echo "pushing to branch ${BRANCH}"
              if [ "$IS_DRY_RUN" = "true" ]; then
                echo "not pushing to branch ${BRANCH} in dry run mode"
              else
                echo "pushing to branch ${BRANCH}"
                git push origin ${BRANCH}
              fi
            else
              echo "Release version ${RELEASE_VERSION} did not change. Nothing to commit."
            fi
          else
            echo "Not auto-updating previousVersion property as release version is not a valid major/minor version."
          fi

      - name: Build Docker Image
        run: |
          tags=""

          echo "Adding tags to release docker image..."

          # Tagging the optimize release Docker image with the specified version
          echo "Tagging optimize release docker image with version ${RELEASE_VERSION}"
          tags=("${DOCKER_IMAGE_TEAM}:${RELEASE_VERSION}")
          tags+=("${DOCKER_IMAGE_DOCKER_HUB}:${RELEASE_VERSION}")

          # Major and minor versions are always tagged as the latest
          if [ "${MAJOR_OR_MINOR}" = true ] || [ "${DOCKER_LATEST}" = true ]; then
              echo "Tagging optimize release docker image with \`${DOCKER_LATEST_TAG}\`"
              tags+=("${DOCKER_IMAGE_TEAM}:${DOCKER_LATEST_TAG}")
              tags+=("${DOCKER_IMAGE_DOCKER_HUB}:${DOCKER_LATEST_TAG}")
          fi

          printf -v tag_arguments -- "-t %s " "${tags[@]}"
          docker buildx create --use

          export VERSION="${RELEASE_VERSION}"
          export DATE="$(date +%FT%TZ)"
          export REVISION="${REVISION}"
          export BASE_IMAGE=docker.io/library/alpine:3.20.0

          # if CI (GHA) export the variables for pushing in a later step
          if [ "${CI}" = "true" ]; then
              echo "DATE=$DATE" >>"$GITHUB_ENV"
              echo "tag_arguments=$tag_arguments" >>"$GITHUB_ENV"
          fi

          docker buildx build \
              ${tag_arguments} \
              --build-arg VERSION="${RELEASE_VERSION}" \
              --build-arg DATE="${DATE}" \
              --build-arg REVISION="${REVISION}" \
              --provenance false \
              --load \
              -f optimize.Dockerfile \
              .

          ./optimize/docker/test/verify.sh "${tags[@]}"

      - name: Start Smoketest
        uses: ./.github/actions/compose
        with:
          compose_file: .github/actions/compose/docker-compose.smoketest.yml
          project_name: smoketest
          timeout: 600
        env:
          OPTIMIZE_IMAGE_TAG: ${{ env.RELEASE_VERSION }}
          ELASTIC_VERSION: ${{ steps.pom-info.outputs.x_elasticsearch8_test_version }}
          ZEEBE_VERSION: ${{ steps.pom-info.outputs.x_zeebe_version }}
          IDENTITY_VERSION: ${{ steps.pom-info.outputs.x_identity_version }}

      - name: Wait for Optimize to start
        run: ./.github/optimize/scripts/wait-for.sh http://localhost:8090/ready

      - name: Execute health check and push docker image
        uses: ./.github/actions/execute-healthcheck-and-push-image
        with:
          version: ${{ env.RELEASE_VERSION }}
          date: ${{ env.DATE }}
          revision: ${{ env.REVISION }}

      - name: Docker log dump
        if: always()
        uses: ./.github/actions/docker-logs
        with:
          archive_name: deploy-artifacts-docker
