
name: Optimize CI
on:
  pull_request:
    paths:
    - ".github/actions/**"
    - ".github/workflows/optimize-*"
    - "bom/*"
    - "parent/*"
    - "pom.xml"
    - "optimize/**"
    - "optimize.Dockerfile"
  push:
    branches:
    - main
    - stable/**
    - release/**
    paths:
    - ".github/actions/**"
    - ".github/workflows/optimize-*"
    - "bom/*"
    - "parent/*"
    - "pom.xml"
    - "optimize/**"
    - "optimize.Dockerfile"
  workflow_dispatch:

# Will limit the workflow to 1 concurrent run per ref (branch / PR)
# If a new commits occurs, the current run will be canceled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# set permissions to allow to publish test results
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  detect-changes:
    name: Get changed directories
    runs-on: ubuntu-latest
    outputs:
      backend-changes: ${{ steps.filter.outputs.backend-changes }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Get list of changed directories
      id: filter
      uses: ./.github/actions/optimize-paths-filter
  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/optimize-unit-tests.yml
    secrets: inherit

  docker:
    if: github.event_name == 'pull_request'
    name: Docker
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Fetch main branch
      run: git fetch origin main:refs/remote/origin/main

    - name: "Read Java / Version Info"
      id: pom-info
      uses: YunaBraska/java-info-action@191c7fcb671125f85486b6fee92b17b180d8e0ab # 2.1.2

    - name: Login to Harbor registry
      uses: ./.github/actions/login-registry
      with:
        secrets: ${{ toJSON(secrets) }}

    - name: Setup Maven
      uses: ./.github/actions/setup-maven
      with:
        secrets: ${{ toJSON(secrets) }}

    - name: Generate production .tar.gz
      uses: ./.github/actions/run-maven
      with:
        parameters: -f optimize/pom.xml install -DskipTests -Dskip.docker -PrunAssembly

    - name: Build and push Docker image
      uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
      with:
        context: .
        file: optimize.Dockerfile
        provenance: false
        build-args: |
          VERSION=${{ steps.pom-info.outputs.project_version }}
          REVISION=${{ github.event.pull_request.head.sha }}
        tags: "registry.camunda.cloud/team-optimize/optimize:pr-${{ github.event.pull_request.head.sha }}"
        push: true

  integration-tests:
    name: Integration Tests
    runs-on: gcp-core-32-default
    timeout-minutes: 120
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.backend-changes == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        includedGroups: [ 'ccsm-test' ]
        include:
        - includedGroups: 'ccsm-test'
          excludedGroups: ''
          profiles: 'ccsm-it'

    steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Fetch main branch
      run: git fetch origin main:refs/remote/origin/main

    - name: Setup Maven
      uses: ./.github/actions/setup-maven
      with:
        secrets: ${{ toJSON(secrets) }}

    - name: Login to Harbor registry
      uses: ./.github/actions/login-registry
      with:
        secrets: ${{ toJSON(secrets) }}

    - name: "Read Java / Version Info"
      id: "pom-info"
      uses: YunaBraska/java-info-action@main

    - name: Expose Parsed Elastic Version
      run: |
        echo "ELASTIC_VERSION=${{ steps.pom-info.outputs.x_elasticsearch8_test_version }}" >> "$GITHUB_ENV"

    - name: Start Elastic
      uses: ./.github/actions/compose
      with:
        compose_file: .github/actions/compose/docker-compose.elasticsearch.yml
        project_name: elasticsearch
      env:
        ELASTIC_VERSION: ${{ env.ELASTIC_VERSION }}
        ELASTIC_JVM_MEMORY: 16
        ELASTIC_HTTP_PORT: 9200

    - name: Verify integration
      uses: ./.github/actions/run-maven
      env:
        LIMITS_CPU: 8
      with:
        threads: 8
        parameters: >
          verify -Dit.test.excludedGroups=${{ matrix.excludedGroups }}
          -Dit.test.includedGroups=${{ matrix.includedGroups }}
          -Dskip.docker -Dskip.fe.build -P${{ matrix.profiles }}
          -Dfailsafe.rerunFailingTestsCount=2
          -Ddatabase.type=elasticsearch -pl optimize/backend -am

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
      with:
        name: integration-test-elasticsearch-${{ matrix.includedGroups }}-junit
        path: |
          **/failsafe-reports/**/*.xml
        retention-days: 7
        if-no-files-found: ignore

    - name: Docker log dump
      uses: ./.github/actions/docker-logs
      if: always()
      with:
        archive_name: integration-tests-elasticsearch-${{ matrix.includedGroups }}-docker

  integration-tests-os:
    name: Integration Tests OpenSearch
    runs-on: gcp-core-32-default
    timeout-minutes: 120
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.backend-changes == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        includedGroups: [ 'ccsm-test' ]
        include:
          - includedGroups: 'ccsm-test'
            excludedGroups: ''
            profiles: 'ccsm-it'

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Fetch main branch
        run: git fetch origin main:refs/remote/origin/main

      - name: Setup Maven
        uses: ./.github/actions/setup-maven
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Login to Harbor registry
        uses: ./.github/actions/login-registry
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: "Read Java / Version Info"
        id: "pom-info"
        uses: YunaBraska/java-info-action@main

      - name: Expose Parsed OpenSearch Version
        run: echo "OPENSEARCH_VERSION=${{ steps.pom-info.outputs.x_opensearch_test_version }}" >> "$GITHUB_ENV"

      - name: Start OpenSearch
        uses: ./.github/actions/compose
        with:
          compose_file: .github/actions/compose/docker-compose.opensearch.yml
          project_name: opensearch
        env:
          OPENSEARCH_VERSION: ${{ env.OPENSEARCH_VERSION }}
          OPENSEARCH_JVM_MEMORY: 16
          OPENSEARCH_HTTP_PORT: 9205

      - name: Verify integration
        uses: ./.github/actions/run-maven
        env:
          LIMITS_CPU: 8
        with:
          threads: 8
          parameters: >
            verify -Dit.test.excludedGroups=${{ matrix.excludedGroups }}
            -Dit.test.includedGroups=${{ matrix.includedGroups }}
            -Dskip.docker -Dskip.fe.build -P${{ matrix.profiles }}
            -Dfailsafe.rerunFailingTestsCount=2
            -Ddatabase.type=opensearch -pl optimize/backend -am

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
        with:
          name: integration-test-opensearch-${{ matrix.includedGroups }}-junit
          path: |
            **/failsafe-reports/**/*.xml
          retention-days: 7
          if-no-files-found: ignore

      - name: Docker log dump
        uses: ./.github/actions/docker-logs
        if: always()
        with:
          archive_name: integration-tests-opensearch-${{ matrix.includedGroups }}-docker

  integration-tests-os-dev:
    name: Integration Tests OpenSearch Development
    runs-on: gcp-core-32-default
    needs: detect-changes
    # checks that the PR isn't closed AND check whether the labeled event contains 'opensearch' as substring || check whether on new commit of PR the label 'opensearch'' is part of label array
    if: github.event.pull_request.state != 'closed' && (contains( github.event.label.name, 'opensearch') || contains( github.event.pull_request.labels.*.name, 'opensearch')) && (needs.detect-changes.outputs.backend-changes == 'true')
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        includedGroups: [ 'reportEvaluation', '' ]
        include:
          - includedGroups: ''
            excludedGroups: 'ccsm-test,import,reportEvaluation'
            profiles: 'it'
          - includedGroups: 'reportEvaluation'
            excludedGroups: ''
            profiles: 'it'
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Fetch main branch
        run: git fetch origin main:refs/remote/origin/main

      - name: Setup Maven
        uses: ./.github/actions/setup-maven
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Login to Harbor registry
        uses: ./.github/actions/login-registry
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: "Read Java / Version Info"
        id: "pom-info"
        uses: YunaBraska/java-info-action@main

      - name: Expose Parsed OpenSearch Version
        run: echo "OPENSEARCH_VERSION=${{ steps.pom-info.outputs.x_opensearch_test_version }}" >> "$GITHUB_ENV"

      - name: Start OpenSearch
        uses: ./.github/actions/compose
        with:
          compose_file: .github/actions/compose/docker-compose.opensearch.yml
          project_name: opensearch
        env:
          OPENSEARCH_VERSION: ${{ env.OPENSEARCH_VERSION }}
          OPENSEARCH_JVM_MEMORY: 16
          OPENSEARCH_HTTP_PORT: 9205

      - name: Verify integration
        uses: ./.github/actions/run-maven
        env:
          LIMITS_CPU: 8
        with:
          threads: 8
          parameters: >
            verify -Dit.test.excludedGroups=${{ matrix.excludedGroups }}
            -Dit.test.includedGroups=${{ matrix.includedGroups }}
            -Dskip.docker -Dskip.fe.build -P${{ matrix.profiles }}
            -Dfailsafe.rerunFailingTestsCount=2
            -Ddatabase.type=opensearch -pl optimize/backend -am

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
        with:
          name: integration-test-opensearch-dev-${{ matrix.includedGroups }}-junit
          path: |
            **/failsafe-reports/**/*.xml
          retention-days: 7
          if-no-files-found: ignore

      - name: Docker log dump
        uses: ./.github/actions/docker-logs
        if: always()
        with:
          archive_name: integration-tests-opensearch-dev-${{ matrix.includedGroups }}-docker

  # Only deploy artifacts on push event, which in this case can only be triggered by main and stable
  deploy-artifacts:
    if: github.event_name == 'push' && (github.ref_name == 'main' || startsWith(github.ref_name, 'stable/'))
    name: Deploy Artifacts
    needs: [unit-tests, integration-tests]
    uses: ./.github/workflows/optimize-deploy-artifacts.yml
    secrets: inherit

  # Rerun failed jobs running on self-hosted runners in case of network issues or node preemption
  rerun-failed-jobs:
    needs:
      - integration-tests
      - integration-tests-os
      - unit-tests
      - deploy-artifacts
    if: failure() && fromJSON(github.run_attempt) < 3
    runs-on: ubuntu-latest
    steps:
      - name: Retrigger job
        uses: camunda/infra-global-github-actions/rerun-failed-run@main
        with:
          error-messages: |
            lost communication with the server
            The runner has received a shutdown signal
          run-id: ${{ github.run_id }}
          repository: ${{ github.repository }}
          vault-addr: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
