name: Optimize Create Release Branch
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true
      release_base_branch:
        description: "Release base branch"
        required: true

jobs:
  create_release_branch:
    name: Create release branch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout release branch
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: ${{ github.event.inputs.release_base_branch }}
          fetch-depth: 0

      - name: Configure GitHub user
        run: |
          git config --global user.name "optimize-release"
          git config --global user.email "ci@optimize.camunda.cloud"

      - name: Create release branch
        run: |
          releaseBranchName="release/optimize-${{ github.event.inputs.release_version }}"
          git checkout -b $releaseBranchName
          git push -u origin $releaseBranchName
